server:
  port: 8104
spring:
  application:
    name: forum-personal
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: localhost
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
#aliyun:
#  oss:
#    access-key-id: LTAI4G3Hx2BRMMsqMV6iQ7gV
#    access-key-secret: HnHOMgpCbXsv91jbEfD9C0SMgU2jLQ
#    bucket-domain: http://visional.oss-cn-shenzhen.aliyuncs.com
#    bucket-name: visional
#    end-point: http://oss-cn-shenzhen.aliyuncs.com