server:
  port: 8104
spring:
  application:
    name: forum-personal
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: localhost
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka