server:
  port: 8101
spring:
  application:
    name: forum-identification
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  redis:
    host: localhost
  session:
    store-type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///forum?useSSL=false&&serverTimezone=UTC
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
#short:
#  message:
#    app-code: 33f9ec5f35cb45238ef6a9559873aaea
#    host: https://smsmsgs.market.alicloudapi.com
#    path: /sms/
#    sign: 151003
#    skin: 84683
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000